version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1009
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 1009
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    image: dochubsang/cicd-server:latest
    container_name: nest-server-contanier
    ports:
      - '3000:3000'
    depends_on:
      - mysql

  client:
    image: dochubsang/cicd-client:latest
    container_name: react-client-container
    ports:
      - '5173:80'
    depends_on:
      - server

volumes:
  mysql-data:
