version: '3.8'

services:
  server:
    image: dochubsang/cicd-server:latest
    container_name: nest-server-contanier
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - '3000:3000'

  client:
    image: dochubsang/cicd-client:latest
    container_name: react-client-container
    ports:
      - '5173:80'
    depends_on:
      - server
